### ISSUE TITLE
ready for production ? 

### ISSUE THREAD

**Issue by crudbug** [masayuki0812/c3#1154]
I am evaluating D3 component libraries for an internal monitoring dashboard project, C3 seems most intuitively aligned with my brain. 

Is it ready for prime-time ?

**Comment by aendrew** [comment]
@crudbug We use it here at The Times and Sunday Times in production pretty extensively, including within our tablet app. There are definitely things you can do to make it leak memory (Calling `c3.generate()` to load in new data instead of using `chart.load()` is a big one), but on a whole it's pretty stable.

**Comment by crudbug** [comment]
@aendrew Thanks 

I have designed the dashboard, I went ahead with C3.
