### ISSUE TITLE
C3 by DOM 

### ISSUE THREAD

**Issue by nOcTIlIoN** [masayuki0812/c3#1478]
Hi all,
I have issue with the DOM declaration of C3. 

```javascript
var CB = $('<div></div>').addClass("infoCB")
    .append('<div id="chart"></div>')
                   

var chart = c3.generate({
    data: {
        bindto: '#chart',
        columns: [
            ['free', 20],
            ['used', 80],
        ],
        width: '100px',
        type: 'donut'
    }
});
```

Why doens't work ?  

I have also tried to add : 

```javascript
$('#chart').data('c3-chart', chart);
```

but nothing changed. Could you please help me ? 

only FYI, the div is .append on click event. 
Thanks a lot, 
NoC

**Comment by lmh** [comment]
The issue here is not related to c3. I believe you have misunderstood what your JQuery statement is doing. For c3.generate to work, the target element must be in the DOM when the method is called. 

Your JQuery creates a pair virtual element (which look like "```<div class='infoCB'><div id='chart'></div></div>```"), but these elements are never added to your page DOM. 

I suspect you want something closer to this:

```
var onClickCallback = function () {
  var CB = $('#someId').addClass("infoCB").append('<div id="chart"></div>');
  var chart = c3.generate({
    data: {
      bindto: CB, // C3 will accept an element reference here, or an ID selector
      columns: [
        ['free', 20],
        ['used', 80],
      ],
      width: '100px',
      type: 'donut'
    }
  });
};
```
As this is not a C3 problem, please close this issue. Support request are better directed to our Gitter channel, or in this case to the JQuery community.

**Comment by aendrew** [comment]
Closing as not an issue.

**Comment by nOcTIlIoN** [comment]
thanks for the replay, I tried but ... doesn't work. Could you suggest me a way to create chart with dynamically div creation ?

**Comment by aendrew** [comment]
Try changing the CB line to this:

```
var CB = $('<div></div>').addClass("infoCB")
    .append('<div id="chart"></div>').appendTo('body');
```

The key is you need to append it somewhere that already exists.

**Comment by MihaiBratulescu** [comment]
I am also having issue turning a DOM element into a chart object. My charts are displayed correctly but  I have more of them and I tryed:

```
$('.c3').each(function () {
                            var chart = $(this).data('c3-chart');
                            chart.flush();//undefined
                        });
```

Any ideeas?

**Comment by aendrew** [comment]
@MihaiBratulescu The `var chart =` line won't do anything because you can't get an instance of C3 from a chart via jQuery. I'd recommend storing the return of c3.generate into an array somewhere and then just iterating through that if you need to flush.

In the future though, please ask support questions on [Gitter](http://gitter.im/masayuki0812/c3/) or the [Google Group](https://groups.google.com/forum/#!forum/c3js)!
