### ISSUE TITLE
Is C3 dead?

### ISSUE THREAD

**Issue by mlajtos** [masayuki0812/c3#1545]
@masayuki0812 has been inactive for few months, last stable release was in March 2015, ... So the question seems relevant.

**Comment by jpruetting** [comment]
I asked a similar question on  #1540

**Comment by mlajtos** [comment]
So we can safely assume that this repo is is dead.

Is there any fork worth looking at? [AO16/c3](https://github.com/AO16/c3) and [bouncelytics/c3](https://github.com/bouncelytics/c3) seems most active.

Btw, does anybody know what happened to @masayuki0812 ?

**Comment by aendrew** [comment]
Hey folks, I don't really any any answer to any of the above (though I will apologise for my own part in being inactive in this project as of late — I'm in the midsts of a book and fifty other things at work), though could you please direct this discussion to #1540 instead? Something definitely needs to be done about the current backlog of PRs/issues (and I honestly don't think at this point I'm the person to do it, especially since I've only ever really been a documentation person on the project), and these are definitely discussions worth having, but please keep them to one issue.

Many thanks. :)

-Æ.
