### ISSUE TITLE
Tooltip on data name ? How to ? 

### ISSUE THREAD

**Issue by collmomo** [masayuki0812/c3#1647]
http://stackoverflow.com/questions/36525550/data-name-adding-data-html-tag?noredirect=1#comment60656125_36525550

**Comment by abacaj** [comment]
I left a comment on stackoverflow - we can follow up here.

`Can you clarify a little bit more? Specifically - the way I understood this question is that you have very long legend names (the way too long bit at the bottom of your donut chart is the legend), and instead of legend names you want a tooltip? Tooltips are already supported in c3. Or did you mean that you want your legend to be "hello" and hover the legend item and display "hello from america"?`

**Comment by abacaj** [comment]
I replied to your question on SO - http://stackoverflow.com/questions/36525550/data-name-adding-data-html-tag/36559342#36559342

**Comment by collmomo** [comment]
Marvellous !! Now, pull request that feature lol !!

**Comment by aendrew** [comment]
That seems like a bit of an edge case. Closing as resolved?
