### ISSUE TITLE
ondragstart and ondragend callbacks prevent scrolling on touch devices

### ISSUE THREAD

**Issue by sandrolino** [masayuki0812/c3#215]
I noticed that c3js graphs disable somewhat scrolling on touch devices, probably due to their interactivity. 
Disabling Tooltip still results in interactivity when hovering over data points. 
Is there away to completely disable hovering over data points (i.e an svg) such that scrolling works on c3js graph works also on touch devices ?

Thanks for your help.
s

**Comment by moklick** [comment]
It would be very helpful if you could add something like swipe detection. By doing this we could interact with the charts even on mobile devices. Right now we have project where we have several charts in an article. Users can't scroll on the charts, so we have to disable interaction which is sad, because interaction works great on mobile devices.

**Comment by aendrew** [comment]
I started a new issue about this recently (since closed) due to having not noticed this one. I'm moving discussion to this thread (and reopening) because there's been more work done here.

Important point from #798: [the problem is in the ondragstart and ondragend callbacks](https://github.com/masayuki0812/c3/issues/798#issuecomment-67310392). Disabling those on ln. 233 in `interaction.js` fixes the scrolling issue while preserving interactivity.

**Comment by moklick** [comment]
@aendrew wow!! thanks you very much. commenting out these lines fixes the problem for us. awesome!

**Comment by aendrew** [comment]
@masayuki0812 Any update on removing those callbacks? Would it help if I did a PR? 

I'm currently integrating [axisJS](http://times.github.io/axisJS) into a Node app that allows C3 charts to be used really effortlessly in news stories; however, it totally causes issues on the iPad due to this issue. I can run off a fork for the moment, but it'd be really nice to be able to get that into core...

**Comment by masayuki0812** [comment]
I added `data.selection.draggable` option that enables dragging to select the points. The default of this option is `false` and then drag interaction will not be added to the chart, so it means we can scroll even if it's on the chart as default.
On the other hand, if we want dragging for data selection, we need to set this option `true`, but I think it's acceptable because the use case seems not much and the scrolling is more important as default interaction.
I believe this fix works for this issue and I'll release the fix in the next version v0.4.9 shortly.

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.

**Comment by aendrew** [comment]
Yay! :+1: :shipit: Nicely done, @masayuki0812!

**Comment by aendrew** [comment]
Adding `documentation` tag re: `data.selection.draggable`.

**Comment by moklick** [comment]
nice! thanks @masayuki0812

**Comment by subu28** [comment]
This issue seems to be persist while using multiple axis using data.xs.

**Comment by bibounet** [comment]
@subu28 same issue for me (using data.xs)
