### ISSUE TITLE
Destroy leaves detached SVG DOM Nodes

### ISSUE THREAD

**Issue by DanielApt** [masayuki0812/c3#866]
When calling `chart.destroy()` I'd imagine all references to DOM Nodes would be cleaned up. This doesn't seem to be the case. I'm not sure if this is a issue with D3 or C3.

I've created a JSFiddle demonstrating this http://jsfiddle.net/DanielApt/7kYJu/853/

The best way to demonstrate it is by using Chrome's Dev Tools. 

1. Click destroy
2. Take a *Heap Snapshot* with Chrome's Dev Tools (it's in the Profiles tab)
3. Change Summary to *Containment*
4. Navigate to the *Detached DOM Trees*

You'll now see a large amount of references to the already removed SVG elements:
![screen shot 2015-01-06 at 18 18 46](https://cloud.githubusercontent.com/assets/52545/5633601/e04782b8-95d0-11e4-9aab-93fa8c28bdb5.png)

A fix is setting to set `chart = null;` as seen in http://jsfiddle.net/DanielApt/to38292b/

I think it would be preferable to make sure C3 cleans the SVG references, instead of the user needing to explicitly set the chart object to null. What are people's thoughts?

**Comment by masayuki0812** [comment]
Thank you very much for your investigation. As you wrote, there are a lot of detached DOM nodes after `destroy` called. Then, I also looked into it and found that we have to release internal variables as well. So, I fixed to assign `null` to each internal variable in `destory`, then now it seems ok.

Btw, `chart = null` is seems not possible because we can't assign `null` to `this` in `destroy`, so we need to do it by ourselves out side of `destroy` like:
```
chart.destroy();
chart = null;
```
However, I modified `destroy` to return `null`, then we can write like this now:
```
chart = chart.destroy(); // chart will be null
```
I think it seems acceptable, but what do you think? If you have any idea, it's welcome :)

**Comment by DanielApt** [comment]
That's more than acceptable, the difference is minute even if somebody uses `chart.destroy()` instead of `chart = chart.destroy()` You've done an awesome job!

I'd update the documentation (can't seem to find it in this repo) to:

destroy()
-------------

Reset the chart object and remove element and events completely.

Arguments: `none`
`.destroy()`

Example:
```
// Destroy the chart
chart.destroy.
```

**Tip** If you have a reference to the chart make sure to call destroy in the following manner:

Example:
```
var chart = c3.generate({...});
chart = chart.destroy();
```

**Comment by masayuki0812** [comment]
The repo for the documentation is here: https://github.com/masayuki0812/c3js.org
Anyway, I'll update it as you suggested. Thanks!

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.

**Comment by scottydelta** [comment]
but does this work if I have say 10 charts on a page and they are all generated using ```c3.generate()```? In my case I cannot called ```destroy()``` before calling next ```c3.generate``` as it would destroy my previous chart.
