### ISSUE TITLE
Unable to view x grid outside the x domain

### ISSUE THREAD

**Issue by dlamotte** [masayuki0812/c3#881]
When charting something progressing towards a goal, it'd be nice to put an x grid line to pin-point the goal.  Typically that goal exists later (when the x-axis is time) than what is visible in the chart.

For instance, on this demo:  http://c3js.org/samples/grid_x_lines.html

Change any of the x grid value's to something greater than 5 and the line will no longer be visible.

**Comment by dlamotte** [comment]
FWIW, I worked around the issue by doing the following:

```
chart.axis.max({x: max});
chart.internal.config.axis_x_tick_values = chart.internal.x.domain();
```

The second problem is that the ticks dont render either.

**Comment by masayuki0812** [comment]
I think you can use `flow` api because it changes x domain and then the grids will be visible. Can you try it? Example is here: http://c3js.org/samples/api_flow.html
And this seems not a bug, so please let me close and could you ask in GoogleGroup first? https://groups.google.com/forum/#!forum/c3js Thanks.
