### ISSUE TITLE
Minimum Browser Requirements 

### ISSUE THREAD

**Issue by skinnybrit51** [masayuki0812/c3#920]
Sorry if I have missed this, but have you documented what minimum version of each browser c3 supports?

**Comment by masayuki0812** [comment]
Basically it's same with d3. We wrote about this in the top page of http://c3js.org/ .

**Comment by skinnybrit51** [comment]
You are using MutationObserver and that is only IE 11+ https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver.  D3 supports IE 9+.

**Comment by masayuki0812** [comment]
You're right. I'll add documentation to inform we need some polyfill as mentioned in #646 to support IE9+.

**Comment by skinnybrit51** [comment]
Maybe the correct solution is to add the polyfill to the c3 code.

**Comment by aendrew** [comment]
@skinnybrit51 We've been [down this path before](https://github.com/masayuki0812/c3/pull/841#issuecomment-68092417), and the consensus is that it's too heavy to polyfill for what is becoming increasingly an edge case. Frankly, it's better to polyfill separately because you can use IE conditional tags to serve the polyfill only to IE <11 and every other browser then doesn't have to deal with that additional ~3kb. 

There's also something to be said for supporting versions of IE with known bugs and security vulnerabilities...

**Comment by megawac** [comment]
> it's better to polyfill separately because you can use IE conditional tags to serve the polyfill only to IE <11 ...

Definitely, people really shouldn't be including that script directly. With amd for instance one would ideally be able to do (untested, I don't use AMD currently).

```js
require.config({
    shim: {
        MutationObserver: {
            exports: 'MutationObserver'
        }
    },
    paths: {
        MutationObserver: window.MutationObserver ? null : "/depends/MutationObserver/dist/mutationobserver.min.js"
    }
});
```

Documenting it is the way to go for sure

**Comment by masayuki0812** [comment]
I updated c3js.org to notice about the supported version of IE and how c3 uses `MutationObserver`. As @aendrew said, we don't think to include polyfill in c3 and please use polyfill based on your requirement.

@megawac Thanks for the information. It would be helpful for us.
