### ISSUE TITLE
samples not working

### ISSUE THREAD

**Issue by lucbonnin** [masayuki0812/c3#923]
On the last release, the samples call js and css with a bad path (on .html samples such as gauge).
You only need to change path to js and css file to a relative

    <script src="/js/c3.js"></script>
to
    <script src="../js/c3.js"></script>

**Comment by aendrew** [comment]
I'll try to confirm this next change I get. Putting `onhold` until I can verify (unless somebody else can?).

**Comment by masayuki0812** [comment]
As you can see in README, please set document root to `htdocs` https://github.com/masayuki0812/c3#tutorial-and-examples

**Comment by aendrew** [comment]
@masayuki0812 To help with getting the examples rolling, do you think it would be a good idea to use something like [grunt-contrib-connect](https://github.com/gruntjs/grunt-contrib-connect) to serve the demos? Would prevent issues like this, ties in with existing infrastructure (I.e., Grunt) and doesn't require Python to be installed. I've also noticed the unminified version of D3 can't be served via SimpleHTTPServer, because it chokes on the [sundry unicode math symbols](https://github.com/mbostock/d3/blob/master/d3.js#L1225) Bostock uses in his code.

[yeoman/generator-angular](http://github.com/yeoman/generator-angular) uses Connect and it works wonderfully. It's super fast and you can tie it to things like `grunt-contrib-watch`, so that it auto-reloads the browser whenever the `watch` task runs. Let me know if you want a PR!

**Comment by KrishnaPG** [comment]
Tried setting the root to `htdocs` - the main sample page loads - but the individual pages have problem. 
Firefox is complaining below:
````
SyntaxError: expected expression, got '.'
````
Chrome complains as:
````
Uncaught SyntaxError: Unexpected token .
simple.html:11 Uncaught ReferenceError: c3 is not defined
````
Wondering if It is valid for a js file to contain redirection just with `../../c3.js` as its content

**Comment by masayuki0812** [comment]
@aendrew Thanks for your advice. `grunt-contrib-connect` looks very nice and I agree with your idea. Did you try it already? If it works well, could you send me a PR?

**Comment by aendrew** [comment]
@masayuki0812 Will do a PR for that today, won't take any time.
