### ISSUE TITLE
0.4.9: charts need manual flush/resize to render data lines

### ISSUE THREAD

**Issue by jarib** [masayuki0812/c3#934]
After upgrading from 0.4.7 to 0.4.9, I noticed that a page I have with 4 c3 charts is not being rendered correctly. 

It can be worked around by doing a manual resize or a call `flush()` on the chart right after `c3.generate()`. It's not completely deterministic, so I think there may be some sort of global state in c3 that's causing this.

Here's an example: http://bl.ocks.org/jarib/raw/d382eb69c0b0737e1785/

The first two charts will have their axes drawn, but no data. 

If you remove the two bottom charts - change `if (true)` to `if (false)` - then the two top charts are rendered correctly.
If you comment in the manual `flush()` calls, everything is rendered correctly.
If you manually resize the window, everything is rendered correctly.

**Comment by aendrew** [comment]
@jarib The first two charts rendered for me... Not sure what I'm doing now.

That said — it seems there's a lot of weirdness around window resizing right now (see #926 in particular, as well as #924). Additionally, see this [modified fiddle](http://jsfiddle.net/9jL1ya9d/2/) from #936 — if you hide the widget and click "Redraw Chart" (i.e., call `generate`), then show the widget, the chart doesn't render. If you hide the widget, resize a viewport and then show it, the chart doesn't render.

**Comment by jarib** [comment]
@aendrew Perhaps you got lucky. Try a hard refresh (Ctrl-Shift-R in Chrome). I'd be suprised if it's consistently working for you. 

Just to be clear, the incorrect rendering of the top chart looks like this:

![image](https://cloud.githubusercontent.com/assets/572/5891311/2f759e94-a48e-11e4-8c69-e303c771a9a4.png)

It should look like this:

![image](https://cloud.githubusercontent.com/assets/572/5891315/468b976e-a48e-11e4-925e-61aa8409bd10.png)

**Comment by aendrew** [comment]
@jarib Lulz, I think I know what's happening — I get a "Do you want to translate this?" bar in Chrome pop up, which effectively triggers a redraw. The charts aren't there before that bar appears. Will investigate...

**Comment by jarib** [comment]
Thanks for looking into this. I'll try `duration: 0` as a workaround for now.

**Comment by ahamid** [comment]
I am sometimes getting similar output, although my problem may be different.  I am trying to `select` bars in a bar chart (timeseries x) right after (or, even, some 50-100ms after) the c3 chart is created (static data).  Sometimes the chart is just empty, but if I hover i can see it is entering bars, but then all sorts of exceptions are thrown about the data being out of range or something.  I have tried postponing until in/after `oninit` callback but this callback seems to happen synchronously anyway and it does not solve the problem.   Even when this particular initialization problem doesn't occur, I still find I need to defer/queue my select calls.  I don't find any documentation on the initialization process of c3 charts.  When exactly is it safe to start interacting with the chart?

**Comment by bjlbernal** [comment]
I came across this as I was looking for a reason why my line-area charts broke when upgrading from 0.4.4 to 0.4.9. Mind you, it only happens when I am using multiple charts on a page with large amounts of data rendering multiple overlapping lines and areas. My individual line-area charts seem to work fine and my collection of short series ranged line-area charts seem to be fine.

Here are a few of my thoughts I'm having around transitions that might help decide what should be done with the transition issue. 

* Why is the transition_duration set to '350' in c3_chart_internal_fn.getDefaultConfig to begin with? It seems to be an arbitrary value and I didn't even notice there was animation.
* Is it more common for charts to be animated or static result outputs? For me they are static. 
* Under what conditions is transition_duration needed? It appears to me that transitions are only needed for animation effects, such as zoom, scroll, flow, resize, and chart changing.
* Although animation can be done with CSS, how will that effect parts like the flow api where I imagine D3 transitions would be needed? 
* Considering @aendrew mentioned setting "chart.transition.duration = 0" and it fixes the issue I was having, why not just set the default to 0 and let transition duration be set and used as needed or desired?

As a side note: I fooled around with increasing the default transition_duration value and got my large data charts at a value of 750 and didn't even notice any transition easing until I got as high as 1350; even then it was quick and almost imperceptible.

**Comment by masayuki0812** [comment]
@bjlbernal Thank you for considering this. The reason why I set the default of `tranisition_duration` to `350` is that c3 focuses on small data basically and I think transition seems making the chart more impressive (if it works well enough). I'm not sure if it's common, but this is just my taste.
However, as you said, the initial transition might not be needed actually and it can be replaced with css animation as @aendrew and should be an option. In my opinion, I don't think we can replace all of transition with css animation as @bjlbernal said, so some transitions will remain.

**Comment by jarib** [comment]
I'm seeing similar odd behaviour with another app now. This time the category label is pushed way off to the side when data is loaded:

![image](https://cloud.githubusercontent.com/assets/572/6200394/844f23a2-b476-11e4-8a7b-d45b89359d80.png)

* This happens even though `chart.transition.duration` is set to 0.
* If I call `chart.flush()` right after `chart.load(...)`, it doesn't help
* If I ```setTimeout(this.chart.flush, 300);``` it **does** help.
* When I manually resize the window, it is rendered correctly.

Here's what it's suposed to look like:

![image](https://cloud.githubusercontent.com/assets/572/6200399/c9a7b306-b476-11e4-91f5-d20e0ec68d1c.png)

**Comment by masayuki0812** [comment]
@jarib Can you try `0.4.10-rc4`? I think this issue is fixed in this version.

**Comment by masayuki0812** [comment]
maybe #975 is related

**Comment by jarib** [comment]
I've updated the gist to use 0.4.10-rc5 and I can no longer reproduce this issue. Thanks!

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close. Thanks!
