### ISSUE TITLE
Pie / Donut chart adding SVG element to body with visibility:hidden, but creates height

### ISSUE THREAD

**Issue by webedge** [masayuki0812/c3#942]
If you notice even on the demo pages:

http://c3js.org/samples/chart_pie.html
http://c3js.org/samples/chart_donut.html

When the data re-loads the scrollbar jumps momentarily. The library is adding an <svg> element to the <body> tag. It is set to have the style visibility=hidden, but it still renders like a block element. To fix for our project I had to add a CSS rule for any child SVG of Body to have a height:0

**Comment by bendrexl** [comment]
Also getting this behavior in Chome (mac osx), though not on Firefox. I have 4 small spline charts on one page, so I don't think this is limited to Pie/Donut variants. 

I'm seeing as many as 10 empty SVG elements being created & immediately destroyed constantly, every second or so.

It wreaks havoc with my other scripts that are sensitive to the page height, and seems to be bogging down the browser when it really gets bad since the entire page is being redrawn constantly (in my case).

![image](https://cloud.githubusercontent.com/assets/5415207/6072221/fb43393c-ad53-11e4-80da-ef1091e69312.png)

**Comment by bendrexl** [comment]
Watch the vertical scroll bar as you mouseover the charts:
http://jsfiddle.net/h6vj9fcn/1/

I also noticed that y-axis ticks are cropped off when I don't have a y-axis label set.

**Comment by masayuki0812** [comment]
Thanks for reporting. I think this is a bug and fixed by the commit above. I changed to set `height:0` for the element inserted when redraw, and I cannot see the scrollbar after this fix.
I'll release this fix in the next version 0.4.10 shortly. Thanks.

**Comment by wallslide** [comment]
I'm getting this problem as well, with the latest version: "0.4.10-rc1" code, using a combo line + bar chart. I can see my scroll bar appearing and disappearing on every update.

**Comment by masayuki0812** [comment]
I think this has been fixed in #1005 and the fix was already released in the latest version `0.4.10`, so let me close at the moment.
