### ISSUE TITLE
C3 not working on Chrome + IE

### ISSUE THREAD

**Issue by Salompas** [masayuki0812/c3#958]
Update 1: Link to fiddle http://jsfiddle.net/xq6wmyvp/

Hello everyone I'm trying to make a pretty simple example work on chrome and IE (not necessary though). It works perfectly on firefox, but nothing appears when I open the html on chrome.

Important information:
1. Using d3 version 3.5.0;
2. Using c3 version 0.4.9;
3. Using bootstrap (v3.3.1) + jquery (v2.1.1) - i don't think the problem is here though;

I tried to create a fiddle with these versions but I couldn't upload new frameworks =/ (any solutions to this?). (sorry i'm a newb T_T).

The code is basically this:
![code](https://cloud.githubusercontent.com/assets/7663115/5975599/dac9c7f0-a869-11e4-8989-cbd0357bc76a.png)

What I get on firefox:
![firefox-code](https://cloud.githubusercontent.com/assets/7663115/5975636/2d72a774-a86a-11e4-91f8-956bf42a88d4.png)

What I get on chrome: (just the 'hello world')
![chrome-code](https://cloud.githubusercontent.com/assets/7663115/5975638/373efc12-a86a-11e4-999a-2463d2056fd0.png)

Can someone help me?
Maybe I should switch d3 version? Or c3? Has anyone faced this problem and found a solution?

Thanks for helping!!!

**Comment by SamMorrowDrums** [comment]
You can add the Javascript dependencies to a fiddle using [CDN JS](https://cdnjs.com/), this is the link to D3 [//cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js](//cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js) 

Or if not there, but the files you need are on Github, you can also use [Raw Git](https://rawgit.com/) then just create a link to a 'raw' file from the Github, and Raw Git will change the headers, so instead of serving it as text (which Github does), Raw Git will serve it as JavaScript.

Here is C.js raw on Gihub: [https://raw.githubusercontent.com/masayuki0812/c3/master/c3.min.js](https://raw.githubusercontent.com/masayuki0812/c3/master/c3.min.js)

And here is the raw git link: [https://rawgit.com/masayuki0812/c3/master/c3.min.js](https://rawgit.com/masayuki0812/c3/master/c3.min.js)

Once you have a JS Fiddle working, you should add it to your question :-D, but I thought I'd answer this part of your question first.

C3 does work in Chrome, IE and FF though. Don't give up.

**Comment by Salompas** [comment]
I will try to create a fiddle now using CDN JS. I know it does, but maybe something weird is happening in d3. Thanks for helping.

**Comment by SamMorrowDrums** [comment]
It is fixed [HERE](http://jsfiddle.net/xq6wmyvp/7/)

Your issue with the fiddle seems to be a [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) issue. JS-Fiddle can't load the CSV directly, and modern browsers won't let you load resources from external websites that don't add the Access-Control-Allow-Origin header, when serving the file.

You won't have that problem, if you host the CSV in the same place as the HTML.

Some browsers might not respect CORS (it is an honour code policy, rather than an enforced law) so it might have worked in some browsers, particularly old ones, but it works perfectly in Chrome for me. I added your file as a Gist on Github.

**Comment by Salompas** [comment]
AWESOME!!!!!!!!!
Your jsfiddle code (http://jsfiddle.net/xq6wmyvp/7/) works perfectly on chrome and on firefox. I updated my code with the link to the .csv and it now works correctly. So the solution is to host the CSV in the same place as the HTML. Somehow chrome won't allow the code to access the csv locally, while firefox does.
Thanks a lot for helping! I can't thank you enough!!!

**Comment by SamMorrowDrums** [comment]
No problem, glad you're sorted.
