### ISSUE TITLE
Data Label Format

### ISSUE THREAD

**Issue by gsklee** [masayuki0812/c3#964]
This example seems to be bugged:

http://c3js.org/samples/data_label_format.html

Labels are not being showed at all.

**Comment by SSchwaiger** [comment]
I'm facing this in my own project as well. The problem seems to be as follows:

$$.selectChart.select('svg').selectAll('.dummy')
            .data([min, max])
            .enter().append('text')
            .text(function (d) { return $$.dataLabelFormat(d.id)(d); })
            .each(function (d, i) {
                lengths[i] = this.getBoundingClientRect()[key] * paddingCoef;
            })
            .remove();


dataLabelFormat(d.id) is supposed to passed the name of the data row into the function but actually "d" is already the data item, the number and therefore the data row identifier is undefined.

**Comment by masayuki0812** [comment]
Sorry I forgot to update the sample. The expected behavior is to set format for each data, not for the axis. So, the sample will be like this:
```
data: {
  labels: {
    format: {
      data1: d3.format('$')
    }
  }
}
```

**Comment by masayuki0812** [comment]
I updated the sample, so let me close at the moment. Thanks.
