### ISSUE TITLE
When are DOM elements created during/after a c3.generate run?

### ISSUE THREAD

**Issue by marco-faustinelli** [masayuki0812/c3#965]
I am writing some code that adds simple graphic elements to the chart. My attempts are frustrated, because at the moment the code runs SVG DOM elements aren't yet available. I assume generate returns immediately and creates them in some other execution flow. 
The only way I see to add my graphics is to put my commands inside a setTimeout call, which is clumsy.
Is there a way to intercept the end of the creation of the DOM elements?
Thank you for your attention.

**Comment by aendrew** [comment]
@marco-faustinelli I haven't used it personally, but would the [onrendered callback](http://c3js.org/reference.html#onrendered) work?

C3 puts all of the DOM elements in the specified SVG area. If you're having problems interacting with them using jQuery, it's because jQuery has issues manipulating the SVG namespace. Try using D3 for that instead.

Closing for the moment; if I haven't answered your question, please just reply and I'll reopen. Thanks! Also, in the future, could you please ask the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) first (if you haven't already done so)? Thanks!
