### ISSUE TITLE
Label text got chop off

### ISSUE THREAD

**Issue by stanfish** [masayuki0812/c3#982]
Looks like there is a bug in calculating the spacing between the border and y-axis.

I have created a friddle to explain this:
http://jsfiddle.net/o3r6km35/2/

Does anyone know what is going on and if there is any workaround? 

Thanks!

**Comment by lilasquared** [comment]
if you add explicit padding it should fix it.  like this
```
bindto: '#chart',
padding: { left: 80 },
```

**Comment by stanfish** [comment]
I see, but that means I have to calculate the correct amount of spacing on my own according to the maximum width among all labels

**Comment by stanfish** [comment]
One temporary workaround is to call flush, then call flush again after 200ms, it will automatically readjust the spacing:
c.flush();
setTimeout(function(){ c.flush(); }, 200);

Does anyone know any better solution?

**Comment by masayuki0812** [comment]
Sorry for this issue, it's a bug and it seems fixed by this commit https://github.com/masayuki0812/c3/commit/4140ceb2fca1aae1e3da95d9984639d0980d29df . This fix was already released as `0.4.10-rc3`, so please try this version for the fix.
Btw, I'll release `0.4.10` shrotly and let you know when it's released. Thanks.

**Comment by stanfish** [comment]
Just confirmed that this issue has been fixed when I tried 0.4.10-rc4, closing this ticket.  Thanks so much!
